<div class="content-rate">
<?php $rate = $block->getRate(); ?>

<?php if(null !== $rate): ?>

<?php 
$newdate = strtotime ( '+7 hour' , strtotime ( $rate->getCreatedAt() ) ) ;
$newdate = date ( 'Y-m-d H:i:s' , $newdate );
?>
<h2>Tỷ giá</h2>
<p>updated on <?php echo "$newdate"; ?></p>

<table >
    <tr>
    <th>Symbol</th>
    <th>Name</th>
    <th>Rate</th>
  </tr>

   <tr>
    <td>USD</td>
    <td>United States Dollar</td>
    <td>1 USD=</td>
  </tr>
    <tr>
    <td>BTC</td>
    <td>  Bitcoin</td>
    <td><?php echo $rate->getBtc(); ?></td>
  </tr>
   <tr>
    <td>EUR</td>
    <td>Euro</td>
    <td><?php echo $rate->getEur(); ?></td>
  </tr>

   <tr>
    <td>JPY</td>
    <td>Japanese Yen</td>
    <td><?php echo $rate->getJpy(); ?></td>
  </tr>
   <tr>
    <td>RUB</td>
    <td>Russian Ruble</td>
    <td><?php echo $rate->getRub(); ?></td>
  </tr>
  
  <tr>
    <td>THB</td>
    <td>Thai Baht</td>
    <td><?php echo $rate->getThb(); ?></td>
  </tr>
   <tr>
    <td>KRW</td>
    <td>South Korean Won</td>
    <td><?php echo $rate->getKrw(); ?></td>
  </tr>
   <tr>
    <td>INR</td>
    <td>Indian Rupee</td>
    <td><?php echo $rate->getInr(); ?></td>
  </tr>
   <tr>
    <td>LAK</td>
    <td>Laotian Kip</td>
    <td><?php echo $rate->getLak(); ?></td>
  </tr>
  <tr>
    <td>VND</td>
    <td>Vietnamese Dong</td>
    <td><?php echo $rate->getVnd(); ?></td>
  </tr>

 
  
</table>
<?php else: ?>
<h2>Data not found</h2>
<?php endif; ?>
</div>